# Generated by Django 4.2.23 on 2025-07-06 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Your first name', max_length=100)),
                ('last_name', models.CharField(help_text='Your last name', max_length=100)),
                ('email', models.EmailField(help_text='Your email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Your phone number (optional)', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Your address (optional)')),
                ('summary', models.TextField(blank=True, help_text='Professional summary or objective (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('position', models.CharField(help_text='Job title/position', max_length=200)),
                ('start_date', models.DateField(help_text='Start date (YYYY-MM-DD)')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if current)', null=True)),
                ('description', models.TextField(help_text='Job description and achievements')),
                ('is_current', models.BooleanField(default=False, help_text='Check if this is your current job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='profiles.profile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill name', max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Proficiency level', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Skill category (e.g., Programming, Languages)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.profile')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='School/University name', max_length=200)),
                ('degree', models.CharField(help_text='Degree or qualification', max_length=200)),
                ('field_of_study', models.CharField(blank=True, help_text='Field of study (optional)', max_length=200)),
                ('start_date', models.DateField(help_text='Start date (YYYY-MM-DD)')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if ongoing)', null=True)),
                ('grade', models.CharField(blank=True, help_text='Grade/GPA (optional)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.profile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
