# Generated by Django 4.2.7 on 2025-07-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='awards',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='publications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='cv',
            name='volunteering',
            field=models.JSONField(default=list),
        ),
    ]
