# Generated by Django 4.2.7 on 2025-07-26 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_generator', '0002_cv_awards_cv_publications_cv_volunteering'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('is_optimized', models.BooleanField(default=False)),
                ('optimization_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cv_generator.cv')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cvtemplate',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='category',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('professional', 'Professional'), ('ats_friendly', 'ATS Friendly')], default='professional', max_length=50),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='color_scheme',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('orange', 'Orange'), ('gray', 'Gray'), ('black', 'Black')], default='blue', max_length=50),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='font_family',
            field=models.CharField(choices=[('arial', 'Arial'), ('times', 'Times New Roman'), ('helvetica', 'Helvetica'), ('georgia', 'Georgia'), ('verdana', 'Verdana')], default='arial', max_length=50),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_previews/'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='template_file',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=50)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cv_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_generator.cvversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
    ]
